# Generated by Django 4.2.20 on 2025-11-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('batch_year', models.CharField(db_index=True, max_length=20)),
                ('percentage10', models.FloatField(blank=True, null=True)),
                ('percentage12', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['batch_year'], name='student360__batch_y_c52e50_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('marks10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('marks12', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('marks10_file', models.FileField(blank=True, null=True, upload_to='marks_cards/10th/')),
                ('marks12_file', models.FileField(blank=True, null=True, upload_to='marks_cards/12th/')),
                ('file10_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file12_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'dob')},
            },
        ),
    ]
