# Generated by Django 4.2.20 on 2025-11-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0002_students_data_admissionstudent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students_data',
            unique_together={('name', 'dob')},
        ),
        migrations.CreateModel(
            name='Mentors_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['department'], name='student360__departm_4d49e0_idx')],
            },
        ),
    ]
