# Generated by Django 4.2.20 on 2025-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0003_alter_students_data_unique_together_mentors_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_data',
            name='branch',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
