# Generated by Django 4.2.20 on 2025-11-17 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0004_students_data_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors_data',
            name='current_student_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentors_data',
            name='max_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students_data',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='student360.mentors_data'),
        ),
    ]
