# Generated by Django 4.2.20 on 2025-11-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0005_mentors_data_current_student_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors_data',
            name='is_password_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentors_data',
            name='password_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentors_data',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
