# Generated by Django 4.2.20 on 2025-11-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0006_mentors_data_is_password_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors_data',
            name='password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
