# Generated by Django 4.2.20 on 2025-11-17 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0007_alter_mentors_data_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiry', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentors_data',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mentors_data',
            name='is_password_set',
        ),
        migrations.RemoveField(
            model_name='mentors_data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mentors_data',
            name='password_token',
        ),
        migrations.RemoveField(
            model_name='mentors_data',
            name='token_expiry',
        ),
        migrations.AddField(
            model_name='mentors_data',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
