# Generated by Django 4.2.20 on 2025-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0008_activationtoken_remove_mentors_data_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors_data',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentors_data',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
