# Generated by Django 4.2.20 on 2025-11-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0010_mentorprofile_remove_mentors_data_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_data',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='student360.student'),
        ),
    ]
