# Generated by Django 4.2.20 on 2025-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0011_students_data_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('10th_marksheet', '10th Marksheet'), ('12th_marksheet', '12th Marksheet'), ('Semester_results', 'Semester results'), ('internship_certificate', 'Internship Certificate'), ('nptel_certificate', 'NPTEL Certificate'), ('course_certificate', 'Course Certificate'), ('skill_certificate', 'Skill Certificate'), ('other', 'Other')], max_length=50),
        ),
    ]
