# Generated by Django 4.2.20 on 2025-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0012_studentdocument_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
