# Generated by Django 4.2.20 on 2025-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0013_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
