# Generated by Django 4.2.20 on 2025-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0014_studentdocument_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_data',
            name='dream',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='students_data',
            name='offer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students_data',
            name='product',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='students_data',
            name='service',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
