# Generated by Django 4.2.20 on 2025-11-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0015_students_data_dream_students_data_offer_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('eligible_batches', models.JSONField(default=list)),
                ('eligible_branches', models.JSONField(default=list)),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_10th', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_12th', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jd_file', models.FileField(blank=True, null=True, upload_to='company_jds/')),
                ('jd_text', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
