# Generated by Django 4.2.20 on 2025-11-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student360', '0017_companyapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyapplication',
            name='ignored',
        ),
    ]
